//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteAhorcado.ECCI {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:ECCI_HolaMundo", ConfigurationName="ECCI.ECCI_HolaMundoPort")]
    public interface ECCI_HolaMundoPort {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ECCI_HolaMundo#HolaMundo#salude", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string salude(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ECCI_HolaMundo#HolaMundo#salude", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> saludeAsync(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ECCI_HolaMundo#HolaMundo#servidorEstampillaDeTiempo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string servidorEstampillaDeTiempo();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ECCI_HolaMundo#HolaMundo#servidorEstampillaDeTiempo", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> servidorEstampillaDeTiempoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ECCI_HolaMundo#HolaMundo#ultimoSaludo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string ultimoSaludo();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ECCI_HolaMundo#HolaMundo#ultimoSaludo", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> ultimoSaludoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ECCI_HolaMundo#HolaMundo#retornaPalabra", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string retornaPalabra();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ECCI_HolaMundo#HolaMundo#retornaPalabra", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> retornaPalabraAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ECCI_HolaMundo#HolaMundo#saludito", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string saludito(string letra);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ECCI_HolaMundo#HolaMundo#saludito", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> saluditoAsync(string letra);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ECCI_HolaMundo#HolaMundo#palabraAdivinada", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        bool palabraAdivinada();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ECCI_HolaMundo#HolaMundo#palabraAdivinada", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<bool> palabraAdivinadaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ECCI_HolaMundo#HolaMundo#letraFallida", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        bool letraFallida();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ECCI_HolaMundo#HolaMundo#letraFallida", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<bool> letraFallidaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ECCI_HolaMundo#HolaMundo#obtenerCantidadErrores", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        [return: System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        string obtenerCantidadErrores();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ECCI_HolaMundo#HolaMundo#obtenerCantidadErrores", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        [return: System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        System.Threading.Tasks.Task<string> obtenerCantidadErroresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ECCI_HolaMundo#HolaMundo#juegoPerdido", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        bool juegoPerdido();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ECCI_HolaMundo#HolaMundo#juegoPerdido", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<bool> juegoPerdidoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ECCI_HolaMundo#HolaMundo#guardarNombreJugador", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        void guardarNombreJugador(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ECCI_HolaMundo#HolaMundo#guardarNombreJugador", ReplyAction="*")]
        System.Threading.Tasks.Task guardarNombreJugadorAsync(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ECCI_HolaMundo#HolaMundo#registrarGanador", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        void registrarGanador();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ECCI_HolaMundo#HolaMundo#registrarGanador", ReplyAction="*")]
        System.Threading.Tasks.Task registrarGanadorAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ECCI_HolaMundoPortChannel : ClienteAhorcado.ECCI.ECCI_HolaMundoPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ECCI_HolaMundoPortClient : System.ServiceModel.ClientBase<ClienteAhorcado.ECCI.ECCI_HolaMundoPort>, ClienteAhorcado.ECCI.ECCI_HolaMundoPort {
        
        public ECCI_HolaMundoPortClient() {
        }
        
        public ECCI_HolaMundoPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ECCI_HolaMundoPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ECCI_HolaMundoPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ECCI_HolaMundoPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string salude(string nombre) {
            return base.Channel.salude(nombre);
        }
        
        public System.Threading.Tasks.Task<string> saludeAsync(string nombre) {
            return base.Channel.saludeAsync(nombre);
        }
        
        public string servidorEstampillaDeTiempo() {
            return base.Channel.servidorEstampillaDeTiempo();
        }
        
        public System.Threading.Tasks.Task<string> servidorEstampillaDeTiempoAsync() {
            return base.Channel.servidorEstampillaDeTiempoAsync();
        }
        
        public string ultimoSaludo() {
            return base.Channel.ultimoSaludo();
        }
        
        public System.Threading.Tasks.Task<string> ultimoSaludoAsync() {
            return base.Channel.ultimoSaludoAsync();
        }
        
        public string retornaPalabra() {
            return base.Channel.retornaPalabra();
        }
        
        public System.Threading.Tasks.Task<string> retornaPalabraAsync() {
            return base.Channel.retornaPalabraAsync();
        }
        
        public string saludito(string letra) {
            return base.Channel.saludito(letra);
        }
        
        public System.Threading.Tasks.Task<string> saluditoAsync(string letra) {
            return base.Channel.saluditoAsync(letra);
        }
        
        public bool palabraAdivinada() {
            return base.Channel.palabraAdivinada();
        }
        
        public System.Threading.Tasks.Task<bool> palabraAdivinadaAsync() {
            return base.Channel.palabraAdivinadaAsync();
        }
        
        public bool letraFallida() {
            return base.Channel.letraFallida();
        }
        
        public System.Threading.Tasks.Task<bool> letraFallidaAsync() {
            return base.Channel.letraFallidaAsync();
        }
        
        public string obtenerCantidadErrores() {
            return base.Channel.obtenerCantidadErrores();
        }
        
        public System.Threading.Tasks.Task<string> obtenerCantidadErroresAsync() {
            return base.Channel.obtenerCantidadErroresAsync();
        }
        
        public bool juegoPerdido() {
            return base.Channel.juegoPerdido();
        }
        
        public System.Threading.Tasks.Task<bool> juegoPerdidoAsync() {
            return base.Channel.juegoPerdidoAsync();
        }
        
        public void guardarNombreJugador(string nombre) {
            base.Channel.guardarNombreJugador(nombre);
        }
        
        public System.Threading.Tasks.Task guardarNombreJugadorAsync(string nombre) {
            return base.Channel.guardarNombreJugadorAsync(nombre);
        }
        
        public void registrarGanador() {
            base.Channel.registrarGanador();
        }
        
        public System.Threading.Tasks.Task registrarGanadorAsync() {
            return base.Channel.registrarGanadorAsync();
        }
    }
}
